version: '3'
services:
  filestorageserver:
    container_name: server
    build: .
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - Sslmode_DB=${Sslmode_DB}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - PATHTOSAVEFILE=${PATHTOSAVEFILE}
      - KEYPASSWORD=${KEYPASSWORD}
      - KEYTOKEN=${KEYTOKEN}
    ports: 
      - "8080:8080"
    volumes:
      - /home/ubuntu/HttpServer/GoGoGo/FileStorageServer/SavedFiles:/appserv/${PATHTOSAVEFILE}
    env_file:
      - .env
    depends_on:
      - mydockerdb          

  mydockerdb:
    container_name: mydockerdb
    build: ./database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - /home/ubuntu/HttpServer/DATEforDBpostgresql:/var/lib/postgresql/data
    env_file:
      - .env
